(pp/pprint (setup-board #{:red :green}))
[{:pieces {:green 6, :red 6}, :symbol :start}
 {:pieces {:green 0, :red 0}, :symbol :bottle}
 {:pieces {:green 0, :red 0}, :symbol :flag}
 {:pieces {:green 0, :red 0}, :symbol :hat}
 {:pieces {:green 0, :red 0}, :symbol :keys}
 {:pieces {:green 0, :red 0}, :symbol :pistol}
 {:pieces {:green 0, :red 0}, :symbol :sword}
 {:pieces {:green 0, :red 0}, :symbol :keys}
 {:pieces {:green 0, :red 0}, :symbol :hat}
 {:pieces {:green 0, :red 0}, :symbol :sword}
 {:pieces {:green 0, :red 0}, :symbol :bottle}
 {:pieces {:green 0, :red 0}, :symbol :pistol}
 {:pieces {:green 0, :red 0}, :symbol :flag}
 {:pieces {:green 0, :red 0}, :symbol :hat}
 {:pieces {:green 0, :red 0}, :symbol :flag}
 {:pieces {:green 0, :red 0}, :symbol :keys}
 {:pieces {:green 0, :red 0}, :symbol :sword}
 {:pieces {:green 0, :red 0}, :symbol :pistol}
 {:pieces {:green 0, :red 0}, :symbol :bottle}
 {:pieces {:green 0, :red 0}, :symbol :flag}
 {:pieces {:green 0, :red 0}, :symbol :bottle}
 {:pieces {:green 0, :red 0}, :symbol :pistol}
 {:pieces {:green 0, :red 0}, :symbol :hat}
 {:pieces {:green 0, :red 0}, :symbol :keys}
 {:pieces {:green 0, :red 0}, :symbol :sword}
 {:pieces {:green 0, :red 0}, :symbol :flag}
 {:pieces {:green 0, :red 0}, :symbol :keys}
 {:pieces {:green 0, :red 0}, :symbol :sword}
 {:pieces {:green 0, :red 0}, :symbol :bottle}
 {:pieces {:green 0, :red 0}, :symbol :hat}
 {:pieces {:green 0, :red 0}, :symbol :pistol}
 {:pieces {:green 0, :red 0}, :symbol :keys}
 {:pieces {:green 0, :red 0}, :symbol :pistol}
 {:pieces {:green 0, :red 0}, :symbol :flag}
 {:pieces {:green 0, :red 0}, :symbol :bottle}
 {:pieces {:green 0, :red 0}, :symbol :sword}
 {:pieces {:green 0, :red 0}, :symbol :hat}
 {:pieces {:green 0, :red 0}, :symbol :boat}]